from Section_Point import Section_Point
from Section import Section
from Axis_Point import Axis_Point
from Support import Support
from Segment import Segment
from sympy import Eq, solve


segments = []
section_points = []
axis_points = []
#A list containing the objects which have an internal force
internal_forces_obj = []

with open("Problems/Exercise_02.txt", "r") as exercise:
    exercise_line = exercise.readlines()
    points_raw = exercise_line[0].strip().split(",")
    for point in points_raw:
        list_point = list(map(float, point.strip("()").split(";")))
        point_section = Section_Point(list_point[0], list_point[1])
        section_points.append(point_section)
    section = Section(section_points)
    for line in exercise_line[1:]:
        line_raw = line.split(";")
        support = Support(line_raw[2])
        axis_point = Axis_Point(line_raw[0], float(line_raw[1]), support,
                                float(line_raw[3]), float(line_raw[4]), float(line_raw[5]))
        axis_points.append(axis_point)
    internal_forces_obj = list(filter(lambda x: x.support.name != "Free", axis_points))


#Checks if the problem is statically determined and returns false otherwise
def integrity_check(points):
    blocked_dof = 0
    for x_point in points:
        blocked_dof += x_point.degrees_of_freedom()
    if blocked_dof > 2:
        return False
    return True


def create_segments(points):
    for i in range(len(points)-1):
        segment = Segment(points[i], points[i+1], points[i].distributed_force)
        segments.append(segment)


#Calculates the sum of the shear forces and returns a simpy equation
def compute_shear_forces_sum(points, segments_y):
    shear_forces_sum = 0
    #To implement reduce
    for point_x in points:
        shear_forces_sum += point_x.concentrated_force
    for segment in segments_y:
        shear_forces_sum += segment.distributed_force*segment.length
    return Eq(sum(x.ya for x in points if x.ya is not None), -1 * shear_forces_sum)


#Calculates the sum of the bending moments and returns a simpy equation
def compute_moments_sum(points, segments_m):
    #Variable containing the sum of all the moments generated by the concentrated forces and the given bending moments
    moments_sum = 0
    #Variable containing the sum of the moments generated by the internal forces as well as the internal moments
    left_hand_side = 0
    #list containing the internal forces, internal_forces[0] will be the point where the moment is calculated
    internal_forces = list(filter(lambda x: x.support.name != "Free", axis_points))
    for point_x in points:
        if point_x.support.name != "Free":
            left_hand_side = point_x.ya*(internal_forces[0].x-point_x.x) + point_x.ma
        else:
            moments_sum += point_x.concentrated_force*(internal_forces[0].x-point_x.x)
    for segment in segments_m:
        if segment.distributed_force != 0:
            moments_sum += segment.distributed_force*segment.length*(internal_forces[0].x - segment.point_2.x
                                                                     - (segment.length/2))
    return Eq(left_hand_side, -1*moments_sum)


if integrity_check(axis_points):
    create_segments(axis_points)
    section.display_section_properties()
    #section.plot_section()
    sum_y = compute_shear_forces_sum(axis_points, segments)
    sum_m = compute_moments_sum(axis_points, segments)
    sol = solve((sum_y, sum_m), [x.ya for x in internal_forces_obj] +
                [x.ma for x in internal_forces_obj if x.ma != 0])
    print(sum_y)
    print(sum_m)
    print(sol)
else:
    print("The problem is statically indeterminate")

